### ISSUE TITLE
Pretrained paccmann_predictor model is saved with different weight names 

### ISSUE THREAD

**Issue by barabadwan** [PaccMann/paccmann_predictor#16] opened 2022-02-01 22:37 UTC
Hi, whenever I try loading the weights for the paccmann_predictor model I get an error involving the state_dict variables 
Can you please advise or perhaps point me to the correct weights file? 
![image](https://user-images.githubusercontent.com/16927097/152063255-55087f53-0e7b-4c93-9aac-70cb7acf307c.png)

**Comment by jannisborn** [comment] 2022-02-01 22:42
Hi @barabadwan,
thanks for the interest in our work. This should be caused by the fact that the repo has evolved from the point in time where we released the trained model. We have tagged the previous version, so please navigate to the root of the repo and do a 
```sh
git checkout 0.0.1
```
(0.0.2 should also work. I think we introduced a change that broke the backwards compatibility in 0.0.3).
I'm closing but feel free to reopen if it persists

**Closed as completed by jannisborn** 2022-02-01 22:42 UTC
